
language: node_js
node_js:
  - "0.10"
  - "0.8"
before_script:
  - "node gcli.js server start --allowexec --websocket &"
script:
  - "node gcli.js test && phantomjs ./phantom-test.js && phantomjs ./phantom-test.js --http"
after_script:
  - "phantomjs ./phantom-test.js --shutdown"

